### ISSUE TITLE
Most OptiX test shaders fail to compile in debug mode with OptiX 8.1

### ISSUE THREAD

**Issue by ksavoie-nv** [shader-slang/slang-rhi#546]
Most of the OptiX test shaders fail to compile for me when I build and run the test suite in debug mode. It looks like we're emitting code for OptiX 9.0 but using older headers. Maybe that code is normally optimized away but is still there when we disable optimizations for debugging?

Here's an example where the code has a variant of `optixGetSphereData` that's only available in 9.0 (note that it isn't actually used in the shader; it's just present in the slang-generated CU file):
```
D:\src\slang-rhi\tests\testing.cpp(225): FATAL ERROR: [Error] [Slang] nvrtc 12.1: default_program(3867): error : argument of type "float4 *" is incompatible with parameter of type "OptixTraversableHandle"
nvrtc 12.1: note :       optixGetSphereData(data);
nvrtc 12.1: note :                          ^
nvrtc 12.1: default_program(3867): error : too few arguments in function call
nvrtc 12.1: note :       optixGetSphereData(data);
```

Here's the full output for ` ray-tracing-triangle-intersection-nonzero-rg-idx.cuda` (which is named `test-ray-tracing-b` at ToT):
```
TEST CASE:  ray-tracing-triangle-intersection-nonzero-rg-idx.cuda

D:\src\slang-rhi\tests\testing.cpp(225): FATAL ERROR: [Error] [Slang] nvrtc 12.1: default_program(3867): error : argument of type "float4 *" is incompatible with parameter of type "OptixTraversableHandle"
nvrtc 12.1: note :       optixGetSphereData(data);
nvrtc 12.1: note :                          ^
nvrtc 12.1: default_program(3867): error : too few arguments in function call
nvrtc 12.1: note :       optixGetSphereData(data);
nvrtc 12.1: note :                              ^
nvrtc 12.1: default_program(3875): error : identifier "optixHitObjectGetSphereData" is undefined
nvrtc 12.1: note :       optixHitObjectGetSphereData(data);
nvrtc 12.1: note :       ^
nvrtc 12.1: default_program(3882): error : argument of type "float4 *" is incompatible with parameter of type "OptixTraversableHandle"
nvrtc 12.1: note :       optixGetLinearCurveVertexData(data);
nvrtc 12.1: note :                                     ^
nvrtc 12.1: default_program(3882): error : too few arguments in function call
nvrtc 12.1: note :       optixGetLinearCurveVertexData(data);
nvrtc 12.1: note :                                         ^
nvrtc 12.1: default_program(3890): error : identifier "optixHitObjectGetLinearCurveVertexData" is undefined
nvrtc 12.1: note :       optixHitObjectGetLinearCurveVertexData(data);
nvrtc 12.1: note :       ^
nvrtc 12.1: default_program(3993): error : identifier "optixHitObjectGetClusterId" is undefined
nvrtc 12.1: note :       return optixHitObjectGetClusterId();
nvrtc 12.1: note :              ^
nvrtc 12.1: default_program(4002): error : no instance of overloaded function "optixMakeMissHitObject" matches the argument list
nvrtc 12.1: note :             argument types are: (uint, float3, float3, float, float, float, OptixRayFlags)
nvrtc 12.1: note :       optixMakeMissHitObject(
nvrtc 12.1: note :       ^
nvrtc 12.1: default_program(4019): error : no instance of overloaded function "optixMakeMissHitObject" matches the argument list
nvrtc 12.1: note :             argument types are: (uint, float3, float3, float, float, float, OptixRayFlags)
nvrtc 12.1: note :       optixMakeMissHitObject(
nvrtc 12.1: note :       ^
nvrtc 12.1: default_program(4232): error : identifier "optixHitObjectSetSbtRecordIndex" is undefined
nvrtc 12.1: note :       optixHitObjectSetSbtRecordIndex(sbtRecordIndex); // returns void
nvrtc 12.1: note :       ^


D:\src\slang-rhi\tests\test-ray-tracing.cpp(310): FATAL ERROR: REQUIRE( !((device->createRayTracingPipeline(rtpDesc, raytracingPipeline.writeRef())) < 0) ) THREW exception: "unknown exception"

ray-tracing-triangle-intersection-nonzero-rg-idx.cuda           FAILED (0.97s)
```

**Comment by ksavoie-nv** [comment]
It works when I build and link Slang ToT instead of 2025.19. I think either the released version is missing a fix or my local build was somehow picking up a stale CUDA prelude.

**Comment by szihs** [comment]
> It works when I build and link Slang ToT instead of 2025.19. I think either the released version is missing a fix or my local build was somehow picking up a stale CUDA prelude.

Seems its not an issue on ToT. I think it might be latest commit 5978f934e (Oct 14) - Added version guards for OptiX 9.0 APIs
